package com.acxdev.poolguardapps.repository

import com.acxdev.poolguardapps.model.coin.Coin

enum class Pool(
    val value: String,
    val domain: String,
    val icon: String,
    val fee: Float,
    val coin: kotlin.collections.List<Coin>,
    val poolStatus: PoolStatus,
    val isListed: Boolean = true
) {
    RAVENPOOL(
        "Ravenpool",
        "https://ravenpool.ninja/",
        "https://ravenpool.ninja/assets/images/logo-icon.png",
        0F,
        PoolCoinList.ravenPoolCoin(),
        PoolStatus.PROGRESS
    ),
    SPACEPOOL(
        "Space Pool",
        "https://pool.space/",
        "https://pool.space/favicon.ico",
        1F,
        emptyList(),
        PoolStatus.PROGRESS
    ),
    LEAFPOOL(
        "LeafPool",
        "https://leafpool.com/",
        "https://www.leafpool.com/favicon.ico",
        1F,
        emptyList(),
        PoolStatus.SOON
    ),
    POOLMOSCOW(
        "Pool-Moscow.ru",
        "https://pool-moscow.ru/",
        "https://i.ibb.co/7JL6FLB/default.png",
        1F,
        emptyList(),
        PoolStatus.SOON
    ),
    DIGIPOOL(
        "Digipools",
        "https://digipools.org/",
        "https://www.digipools.org/img/fav/favicon-96x96.png",
        1F,
        emptyList(),
        PoolStatus.SOON
    ),
    SEROPOOL(
        "SERO Pool",
        "https://pool.sero.cash/",
        "https://i.ibb.co/7JL6FLB/default.png",
        0.5F,
        emptyList(),
        PoolStatus.SOON
    ),
    EZIL_ZIL(
        "Ezil Dual Mining (+ ZIL)",
        "https://ezil.me/",
        "https://ezil.me/static/favicon.ico",
        1F,
        PoolCoinList.ezilCoin(),
        PoolStatus.ACTIVE
    ),
    FLOCKPOOL(
        "Flockpool",
        "https://flockpool.com/",
        "https://flockpool.com/favicon-32x32.png",
        1.5F,
        PoolCoinList.flockPoolCoin(),
        PoolStatus.ACTIVE
    ),
    ZETPOOLPPS(
        "ZETpool PPS",
        "https://zet-tech.eu/",
        "https://i.ibb.co/q1Tm2CF/zet-Custom.png",
        0.5F,
        PoolCoinList.zetPoolPpsCoin(),
        PoolStatus.ACTIVE
    ),
    UNMINEABLE(
        "unMineable",
        "https://unmineable.com/",
        "https://unmineable.com/img/favicon.png",
        1F,
        PoolCoinList.unMineableCoin(),
        PoolStatus.ACTIVE
    ),
    MINERPOOLSOLO(
        "MinerPool SOLO",
        "https://minerpool.org/",
        "https://minerpool.org/images/logo-favicon.png",
        1F,
        PoolCoinList.minerPoolSoloCoin(),
        PoolStatus.ACTIVE
    ),
    MINERPOOL(
        "MinerPool",
        "https://minerpool.org/",
        "https://minerpool.org/images/logo-favicon.png",
        1F,
        PoolCoinList.minerPoolCoin(),
        PoolStatus.ACTIVE
    ),
    CRUXPOOL(
        "Cruxpool",
        "https://cruxpool.com/",
        "https://cruxpool.com/favicon.ico",
        1F,
        emptyList(),
        PoolStatus.SOON,
        false
    ),
    EZIL(
        "Ezil",
        "https://ezil.me/",
        "https://ezil.me/static/favicon.ico",
        1F,
        PoolCoinList.ezilCoin(),
        PoolStatus.ACTIVE
    ),
    //TODO ETH DEAD
    HIVEON(
        "Hiveon",
        "https://hiveon.net/",
        "https://i.ibb.co/VxswQWG/1-Fcf-R0dcd-GWBDhty-W2tu86g-Custom.png",
        0F,
        PoolCoinList.hiveOnCoin(),
        PoolStatus.ACTIVE
    ),
    RAVENMINER(
        "RavenMiner",
        "https://ravenminer.com/",
        "https://i.ibb.co/ScxGB8L/ravenminer.png",
        0.5F,
        PoolCoinList.ravenMinerCoin(),
        PoolStatus.ACTIVE
    ),
    COMINERS(
        "Cominers",
        "https://cominers.org/",
        "https://cominers.org/images/favicon.ico",
        1F,
        PoolCoinList.coMinersCoin(),
        PoolStatus.ACTIVE
    ),
    //TODO CHECK
    MYMINERSSOLO(
        "MyMiners SOLO",
        "https://myminers.org/",
        "https://myminers.org/favicon.ico",
        1F,
        PoolCoinList.myMinersSoloCoin(),
        PoolStatus.ACTIVE
    ),
    //TODO CHECK
    MYMINERS(
        "MyMiners",
        "https://myminers.org/",
        "https://myminers.org/favicon.ico",
        1F,
        PoolCoinList.myMinersCoin(),
        PoolStatus.ACTIVE
    ),
    MINEXMR(
        "MINEXMR",
        "https://minexmr.com/",
        "https://minexmr.com/favicon.ico",
        1F,
        PoolCoinList.mineXmrCoin(),
        PoolStatus.ACTIVE
    ),
    ETHO(
        "Etho.Club",
        "https://etho.club/",
        "https://etho.club/favicon.ico",
        1F,
        PoolCoinList.ethoClubPoolCoin(),
        PoolStatus.ACTIVE
    ),
    BAIKALMINESOLO(
        "BaikalMine SOLO",
        "https://baikalmine.com/",
        "https://baikalmine.com/favicon.ico",
        1F,
        PoolCoinList.baikalMineSoloCoin(),
        PoolStatus.ACTIVE
    ),
    BAIKALMINEPPS(
        "BaikalMine PPS+",
        "https://baikalmine.com/",
        "https://baikalmine.com/favicon.ico",
        0.5F,
        PoolCoinList.baikalMinePpsCoin(),
        PoolStatus.ACTIVE
    ),
    BAIKALMINE(
        "BaikalMine",
        "https://baikalmine.com/",
        "https://baikalmine.com/favicon.ico",
        0.5F,
        PoolCoinList.baikalMineCoin(),
        PoolStatus.ACTIVE
    ),
    WOOLYPOOLYSOLO(
        "WoolyPooly SOLO",
        "https://woolypooly.com/",
        "https://woolypooly.com/favicon.ico",
        0.9F,
        PoolCoinList.woolyPoolyCoin(),
        PoolStatus.ACTIVE
    ),
    SOLOPOOL(
        "SoloPool",
        "https://solopool.org/",
        "https://solopool.org/favicon.ico",
        1.5F,
        PoolCoinList.soloPoolCoin(),
        PoolStatus.ACTIVE
    ),
    TWOMINERSSOLO(
        "2Miners SOLO",
        "https://2miners.com/",
        "https://2miners.com/favicon.ico",
        1.5F,
        PoolCoinList.twoMinersSoloCoin(),
        PoolStatus.ACTIVE
    ),
    K1POOLSOLO(
        "K1Pool SOLO",
        "https://k1pool.com/",
        "https://k1pool.com/favicon.ico",
        1F,
        PoolCoinList.k1PoolSoloCoin(),
        PoolStatus.ACTIVE
    ),
    K1POOLRBPPS(
        "K1Pool RBPPS+",
        "https://k1pool.com/",
        "https://k1pool.com/favicon.ico",
        1F,
        PoolCoinList.k1PoolRbppsCoin(),
        PoolStatus.ACTIVE
    ),
    K1POOL(
        "K1Pool",
        "https://k1pool.com/",
        "https://k1pool.com/favicon.ico",
        1F,
        PoolCoinList.k1PoolCoin(),
        PoolStatus.ACTIVE
    ),
    LUCKPOOL(
        "LuckPool",
        "https://luckpool.net/",
        "https://luckpool.net/assets/img/logo.png",
        1F,
        PoolCoinList.luckPoolCoin(),
        PoolStatus.ACTIVE
    ),
    TWOMINERS(
        "2Miners",
        "https://2miners.com/",
        "https://2miners.com/favicon.ico",
        1F,
        PoolCoinList.twoMinersCoin(),
        PoolStatus.ACTIVE
    ),
    ZETPOOL(
        "ZETpool",
        "https://zet-tech.eu/",
        "https://i.ibb.co/q1Tm2CF/zet-Custom.png",
        0.5F,
        PoolCoinList.zetPoolCoin(),
        PoolStatus.ACTIVE
    ),
    CRAZYPOOL(
        "CrazyPool",
        "https://crazypool.org/",
        "https://i.ibb.co/VvpL8ms/crazypool.png",
        1F,
        PoolCoinList.crazyPoolCoin(),
        PoolStatus.ACTIVE
    ),
    WOOLYPOOLY(
        "WoolyPooly",
        "https://woolypooly.com/",
        "https://woolypooly.com/favicon.ico",
        0.9F,
        PoolCoinList.woolyPoolyCoin(),
        PoolStatus.ACTIVE
    ),
    HEROMINERS(
        "HeroMiners",
        "https://herominers.com/",
        "https://i.ibb.co/VJXJcJ1/apple-icon-120x120.png",
        0.9F,
        PoolCoinList.heroMinersCoin(),
        PoolStatus.ACTIVE
    ),
    NANOPOOL(
        "Nanopool",
        "https://nanopool.org/",
        "https://nanopool.org/favicon.ico",
        1F,
        PoolCoinList.nanoPoolCoin(),
        PoolStatus.ACTIVE
    ),
    FLEXPOOL(
        "Flexpool",
        "https://flexpool.io/",
        "https://i.ibb.co/85mLJzk/icon.png",
        1F,
        PoolCoinList.flexPoolCoin(),
        PoolStatus.ACTIVE
    ),
    FLYPOOL(
        "Flypool",
        "https://flypool.org/",
        "https://ethermine.org/favicon.ico",
        1F,
        PoolCoinList.flyPoolCoin(),
        PoolStatus.ACTIVE
    ),
    ETHERMINE(
        "Ethermine",
        "https://ethermine.org/",
        "https://ethermine.org/favicon.ico",
        1F,
        PoolCoinList.etherMineCoin(),
        PoolStatus.ACTIVE
    ),
}