package com.acxdev.poolguardapps.model

data class WhattomineCoins (val coins: Map<String, PuneHedgehog>)

data class PuneHedgehog (
    val id: Long,
    val tag: String,
    val algorithm: String,
    val block_time: Double,
    val block_reward: Double,
    val block_reward24: Double,
    val last_block: Long,
    val difficulty: Double,
    val difficulty24: Double,
    val nethash: Double,
    val exchange_rate: Double,
    val exchange_rate24: Double,
    val exchange_rate_vol: Double,
    val exchange_rate_curr: String,
    val market_cap: String,
    val estimated_rewards: String,
    val estimated_rewards24: String,
    val btc_revenue: String,
    val btc_revenue24: String,
    val profitability: Long,
    val profitability24: Long,
    val lagging: Boolean,
    val timestamp: Long
)

data class Profit(val symbol: String, val algorithm: String, val revenue: String, val profit: String)

enum class MapCoin(val value: String){
    Ethereum("Ethereum"),
    NicehashEthash("Nicehash-Ethash"),
    Ergo("Ergo"),
    Ravencoin("Ravencoin"),
    NicehashAutolykos("Nicehash-Autolykos"),
    EthereumClassic("EthereumClassic"),
    NicehashKawPow("Nicehash-KawPow"),
    Beam("Beam"),
    QuarkChain("QuarkChain"),
    Vertcoin("Vertcoin"),
    NicehashBeamV3("Nicehash-BeamV3"),
    Metaverse("Metaverse"),
    Zano("Zano"),
    Etho("Etho"),
    Bloc("Bloc"),
    Conceal("Conceal"),
    Flux("Flux"),
    Callisto("Callisto"),
    Equilibria("Equilibria"),
    Ryo("Ryo"),
    Expanse("Expanse"),
    Swap("Swap"),
    BitTubeCash("BitTubeCash"),
    HavenProtocol("HavenProtocol"),
    Zclassic("Zclassic"),
    Ellaism("Ellaism"),
    Aeternity("Aeternity"),
    Ubiq("Ubiq"),
    Ycash("Ycash"),
    NicehashCuckooCycle("Nicehash-CuckooCycle"),
    BitcoinGold("BitcoinGold"),
    Tent("Tent"),
    NicehashNeoScrypt("Nicehash-NeoScrypt"),
    BitcoinZ("BitcoinZ"),
    NicehashZhash("Nicehash-Zhash"),
    Firo("Firo"),
    Aion("Aion"),
    EtherGem("EtherGem"),
    Vidulum("Vidulum"),
    Trezarcoin("Trezarcoin"),
    Zero("Zero"),
    MWCCT31("MWC-CT31"),
    Zero1coin("01coin"),
    GoByte("GoByte"),
    Conflux("Conflux"),
    BitCash("BitCash"),
    Masari("Masari"),
    Feathercoin("Feathercoin"),
    GrinCT32("Grin-CT32"),
    Lethean("Lethean"),
    NicehashCuckatoo32("Nicehash-Cuckatoo32"),
    NicehashCuckatoo31("Nicehash-Cuckatoo31"),
    NicehashOctopus("Nicehash-Octopus"),
    Sumokoin("Sumokoin"),
    Sinovate("Sinovate"),
    NicehashCryptoNightR("Nicehash-CryptoNightR"),
    EtherSocial("EtherSocial"),
    QuantumRL("Quantum R L"),
    Monero("Monero"),
    NicehashRandomX("Nicehash-RandomX"),
    Sero("Sero")
}